"""Initial migration.

Revision ID: f0d241772c6c
Revises: 
Create Date: 2023-04-22 17:31:11.936326

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Column, String, ForeignKey

# revision identifiers, used by Alembic.
revision = 'f0d241772c6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weapons', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weapons', schema=None) as batch_op:
        batch_op.add_column('weapons',
            Column('image', String())
        )

    # ### end Alembic commands ###
